version: '2'
services:
   corenlp:
     image: sld3/corenlp:3.6.0
     ports:
       - 9000:9000
   opennmt:
      image: sld3/opennmt
      ports:
        - 5556:5556
      volumes:
        - ./data:/root/data
      command: 'bash -c "cd /root/opennmt && th tools/translation_server.lua -host 0.0.0.0 -port 5556  -model /root/data/model.t7 -beam_size 12"'
      stdin_open: true
      tty: true
